version: '3'

services:
  db:
    image: postgres:15
    container_name: pos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=talkie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - default
  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"
  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations accounts &&
             python manage.py migrate &&
             daphne chatapp.asgi:application -b 0.0.0.0 -p 8000"
    # daphne chatapp.asgi:application -b 0.0.0.0 -p 8000
    image: phucduogth1/talkie-server:amd
    container_name: talkie-container
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=talkie
      - DB_USER=postgres
      - DB_PASSWORD=postgres
volumes:
  postgres_data: