# Generated by Django 4.1.7 on 2023-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='message',
            name='sticker',
            field=models.URLField(blank=True, null=True),
        ),
    ]
