# Generated by Django 4.1.7 on 2023-03-08 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_emoji_alter_message_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
    ]
